version: ‘3.4’
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: fiek
      POSTGRES_PASSWORD: fiek
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
  kibana:
    image: kibana:8.2.2
    container_name: kibana
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - elastic
  elasticsearch:
    image: elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: fiek@uni-pr.edu
      PGADMIN_DEFAULT_PASSWORD: fiek
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 8080:80
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
  elastic:
    driver: bridge
volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local
  es_data:
    driver: local
